class Report < ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[Report, Report::ActiveRecord_Relation]

  attr_accessor id (): Integer
  attr_accessor server_id (): Integer
  attr_accessor datetime (): Time
  attr_accessor branch (): String
  attr_accessor revision (): Integer
  attr_accessor summary (): String
  attr_accessor created_at (): Time
  attr_accessor updated_at (): Time
  attr_accessor option (): String
  attr_accessor ltsv (): String

  def server: () -> Server

  def sha1: () -> String

  def revisionuri: () -> String?

  def meta_ruby_repo_key: () -> nil

  def dt: () -> String

  def jstdt: () -> String

  def sjstdt: () -> String

  def patchlevel: () -> String?

  def build: () -> String?

  def btest: () -> String?

  def testknownbug: () -> String?

  def test: () -> String?

  def testall: () -> String?

  def rubyspec: () -> String?

  def shortsummary: () -> String?

  def diffstat: () -> String?

  def depsuffixed_name: () -> String?

  def branch_opts: () -> String?

  def loguri: () -> String

  def diffuri: () -> String

  def failuri: () -> String?

  def recenturi: () -> String

  def meta: () -> Hash[String, String]?

 def self.store_log: (Integer server_id, Net::HTTP http, String path, Time datetime, String branch, String option, Integer revision, String ltsv, String summary, String? depsuffixed_name) -> void
  def self.sql_datetime: (String col) -> String

  def self.scan_recent: (Server server, String? depsuffixed_name, String body, Net::HTTP http, String recentpath) -> void

  def self.scan_recent_ltsv: (Server server, String? depsuffixed_name, String body, Net::HTTP http, String recentpath) -> void

  def self.get_reports: (Server server) -> void

  def self.fetch_recent: () -> void

  def self.post_recent: () -> void
end

Report::REG_RCNT: Regexp

class Report::ActiveRecord_Relation < ActiveRecord::Relation
  include _ActiveRecord_Relation[Report]
  include Enumerable[Report, self]
end

class Report::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
