class Net::HTTPResponse
  def value: () -> void
end

class Net::HTTP
  def self.start: (Integer, String, ?open_timeout: Integer, ?read_timeout: Integer) { (instance) -> void } -> void
  def get: (String) -> Net::HTTPResponse
end
